
spring:
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      #设置 id 自增
      id-type: auto
  configuration:
    #设置 mybatis-plus log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

logging:
  level:
    root: info
